# Generated by Django 3.1.5 on 2021-01-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210112_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='imageicon.png', null=True, upload_to='image/'),
        ),
    ]
