# Generated by Django 3.1.5 on 2021-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210113_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image/imageicon.png', null=True, upload_to='image/'),
        ),
    ]
